### ISSUE TITLE
Consistency in PA-Mac (based on PA-Windows)

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#207]
some things we discussed before, please extend:

- [x]  make sure trackers are named the same as their windows pendant
- [ ]  consistent port number for visualization (i.e. local server)
- [ ]  consistent use of IVisualization interface
- [x]  consistent use of ITracker interface
- [x]  app and process name should be "PersonalAnalytics"
- [x]  app-icon 
- [ ] we should start a list to describe and compare mac-windows where the trackers are the same and where not
- [ ]  ...

**Comment by casaout** [comment]
@csatterfield Here you find the updated icons (also a black version for Mac): https://github.com/sealuzh/PersonalAnalytics/tree/dev-am/src/client/AM.PA.MonitoringTool/PersonalAnalytics/Assets

**Comment by csatterfield** [comment]
Regarding ITracker interface: it seems like in the Windows version each tracker is responsible for creating and updating its own data tables? This wont be possible in the current implementation of the Mac version, since its using Core Data for persistence which requires a model the data model to be updated every time a new table is added. It might be best if we switch to our own database implementation at some point, to preserve the ease of adding or removing trackers that the windows version has (also it will fix the Z thing).

**Comment by casaout** [comment]
hi @csatterfield 
Exactly. The idea is to keep the trackers separate from PersonalAnalytics *and* the other data trackers as much as possible. This has advantages such as flexibility, easier maintenance etc.

What if the database access (i.e. the basic calls) is in a shared library (like it is in the Windows version) and every time a table is added, it fetches the models from each tracker to update the persistence model? (i.e. add a method GetDatabaseModel(..) or similar to the ITracker interface and call it whenever the database structure is updated. Could this work?


Is there possibly any other implementation for persistence with SQLite? Or how much effort would it take to build our own implementation?

thanks!

**Comment by royru** [comment]
Hi, based on last weeks chat I am adding myself to the list of assignees :)

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
