### ISSUE TITLE
Improve DateTime Logging when TimeZones change

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#65]
The current implementation of the whole system logs the current DateTime object. This is fine as long as the user only accesses local data, but doesn't work anymore in case other data sources (e.g. sensor data) is used.

The goal is to find a good way for existing and new users to update this and use DateTimeOffset (i.e. neutral time):
- [ ] Find good way to make the change to DateTimeOffset
- [ ] Create migration tool for existing users
- [ ] NEW: update cached timezone info to have correct times in the database entries (likely reconnect to database)
- [ ] Test!

**Comment by casaout** [comment]
"If you are saving the offset, it is usually beneficial to save all dates in UTC (especially in a db) so you won't have to deal with offsets. You simply convert them before displaying but do all calculations in UTC."

From: http://stackoverflow.com/questions/6284124/get-datetimeoffset-from-datetime-utc-and-timezoneinfo

**Comment by tzimmermsr** [comment]
Not sure if saving in UTC is the best option, since most times you need the local time. It also makes it harder for the user to explore their own data file.

The UTC time is mostly needed for integrating with other data sources.

--Tom

**Comment by casaout** [comment]
I am not sure either, but that's what I read as suggestions/beest practices on various pages when I was exploring options... Their reasoning is that everything is always stored in UTC time (i.e. universal time) and we let the client handle the conversion to the local time.

Another source: http://stackoverflow.com/questions/7577389/how-to-elegantly-deal-with-timezones

Is your suggestion to just save the timezone with every entry or save the universal time and the local time for each entry? (might result in some overhead...)

**Comment by tzimmermsr** [comment]
Yes, but all this advice is for things like “hosted in a different time zone than the users using the application”

In most cases, the retrospection will be on the same time zone and the monitors. If you do UTC you will also have to convert.

Also for retrospection, you don’t necessarily want to convert to the current time zone, you want to convert to the time zone where the user was when the entry was created. Say, you are going on a trip to Japan, you don’t want your activity in Seattle time because you are doing that activity in Japan. Even after you get back that activity will still have occurred in Japan time.

I think that you can’t avoid saving the time zone for every entry (or some clever way to infer it from some other entry but that’s not straightforward). Saving UTC and local time is also an option, but increases space requirements.

--Tom

**Comment by casaout** [comment]
Yes, you are right. My idea now is to add the timezone info to each timestamp entry (as it's a string anyway as SQlite doesn't have DateTime-types). If this doesn't work, I'll add a TimeZone-Id column for each entry.

For now, the temporary workaround (https://github.com/sealuzh/PersonalAnalytics/commit/01c853f20b65b6dff8d185eef9b240080209d696) is to save every timezone change in a separate table.

**Comment by tzimmermsr** [comment]
Sounds good.

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
